universe:
  name: us_top50_liquid_v1
  rebalance: monthly
  symbols:
    - AAPL
    - MSFT
    - NVDA
    - AMZN
    - GOOGL
    - META
    - TSLA
    - AVGO
    - AMD
    - ORCL
    - CRM
    - ADBE
    - CSCO
    - QCOM
    - AMAT
    - TXN
    - NFLX
    - INTC
    - IBM
    - INTU
    - PLTR
    - JPM
    - BAC
    - WFC
    - GS
    - MS
    - V
    - MA
    - AXP
    - BRK.B
    - LLY
    - ABBV
    - UNH
    - MRK
    - ABT
    - TMO
    - XOM
    - CVX
    - CAT
    - GE
    - RTX
    - BA
    - WMT
    - COST
    - HD
    - PG
    - KO
    - MCD
    - DIS
    - UBER
