"""Leakage-safe nonlinear directional model for the Adaptive Net Utility strategy.

The model predicts 10-session forward return from the same point-in-time feature
contract already available to Strategy League. Training uses scikit-learn, but
serving uses the pure-Python HistGradientBoosting interpreter shared with
``robust_range_v3``.

Model selection is deliberately aligned with trading economics: hyperparameters
are chosen on purged temporal folds using cost-adjusted long/short tail returns,
not in-sample regression fit. Validation selects only the operating threshold;
the blind test is opened once after every choice is frozen.
"""

from __future__ import annotations

import argparse
import json
import math
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from statistics import fmean, median
from typing import Any

from models.robust_range_v3 import export_hist_gradient_boosting, predict_head
from models.temporal_cv import purged_expanding_folds
from models.train_weekly_opportunity import (
    predict_weekly_opportunity,
    train_weekly_opportunity_model,
)


MODEL_NAME = "adaptive_net_utility_hgb"
MODEL_VERSION = "v1"
TARGET_END_FIELD = "target_end_date_q1"
TARGET_FIELD = "forward_return_q1"
TARGET_CLIP = 0.20
DEFAULT_ROUND_TRIP_COST = 0.0058

# Keep the model's production feature contract intentionally small. Every field
# below is already generated by league.market_features._feature_row, so a model
# that wins offline can be replayed and served without silently changing inputs.
FEATURE_NAMES: tuple[str, ...] = (
    "momentum_20",
    "rel_strength_20",
    "trend_context_m3",
    "drawdown_13w",
    "atr_ratio_14",
    "price_position_in_range_20",
)

HYPERPARAMETER_GRID: tuple[dict[str, float | int | bool | str], ...] = (
    {
        "loss": "squared_error",
        "learning_rate": 0.03,
        "max_iter": 80,
        "max_leaf_nodes": 3,
        "min_samples_leaf": 80,
        "l2_regularization": 0.5,
        "early_stopping": False,
        "random_state": 401,
    },
    {
        "loss": "squared_error",
        "learning_rate": 0.04,
        "max_iter": 100,
        "max_leaf_nodes": 5,
        "min_samples_leaf": 80,
        "l2_regularization": 0.8,
        "early_stopping": False,
        "random_state": 402,
    },
    {
        "loss": "squared_error",
        "learning_rate": 0.04,
        "max_iter": 120,
        "max_leaf_nodes": 5,
        "min_samples_leaf": 120,
        "l2_regularization": 1.5,
        "early_stopping": False,
        "random_state": 403,
    },
    {
        "loss": "squared_error",
        "learning_rate": 0.03,
        "max_iter": 120,
        "max_leaf_nodes": 7,
        "min_samples_leaf": 120,
        "l2_regularization": 2.0,
        "early_stopping": False,
        "random_state": 404,
    },
)

OPERATING_GRID: tuple[tuple[float, float], ...] = (
    (0.10, 0.006),
    (0.10, 0.008),
    (0.15, 0.006),
    (0.15, 0.008),
    (0.15, 0.010),
    (0.20, 0.008),
    (0.20, 0.010),
)


@dataclass(frozen=True)
class SelectionMetrics:
    trades: int
    dates: int
    mean_net_return: float
    median_net_return: float
    hit_rate: float
    mean_daily_selection_return: float
    worst_decile_trade_return: float
    rank_correlation: float

    def as_dict(self) -> dict[str, float | int]:
        return {
            "trades": self.trades,
            "dates": self.dates,
            "mean_net_return": self.mean_net_return,
            "median_net_return": self.median_net_return,
            "hit_rate": self.hit_rate,
            "mean_daily_selection_return": self.mean_daily_selection_return,
            "worst_decile_trade_return": self.worst_decile_trade_return,
            "rank_correlation": self.rank_correlation,
        }


def _number(value: object, default: float = 0.0) -> float:
    if isinstance(value, bool) or value is None:
        return default
    try:
        result = float(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return default
    return result if math.isfinite(result) else default


def feature_map(row: dict[str, Any]) -> dict[str, float]:
    close = max(_number(row.get("close")), 1e-6)
    return {
        "momentum_20": _number(row.get("momentum_20")),
        "rel_strength_20": _number(row.get("rel_strength_20")),
        "trend_context_m3": _number(row.get("trend_context_m3")),
        "drawdown_13w": _number(row.get("drawdown_13w")),
        "atr_ratio_14": abs(_number(row.get("atr_14"))) / close,
        "price_position_in_range_20": _number(
            row.get("price_position_in_range_20"), 0.5
        ),
    }


def _target(row: dict[str, Any]) -> float | None:
    if row.get("split_eligible_q1", True) is False:
        return None
    raw = row.get(TARGET_FIELD)
    if raw in (None, ""):
        return None
    value = _number(raw, float("nan"))
    if not math.isfinite(value):
        return None
    return max(-TARGET_CLIP, min(TARGET_CLIP, value))


def usable_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [row for row in rows if _target(row) is not None]


def _fit_head(
    rows: list[dict[str, Any]],
    hyperparameters: dict[str, float | int | bool | str],
) -> dict[str, Any]:
    usable = usable_rows(rows)
    if not usable:
        raise ValueError("adaptive utility model requires labeled q1 rows")
    try:
        import numpy as np
        from sklearn.ensemble import HistGradientBoostingRegressor
    except ImportError as exc:  # pragma: no cover - Actions installs dev deps
        raise RuntimeError("adaptive utility training requires modeling dependencies") from exc

    matrix = np.asarray(
        [[feature_map(row)[name] for name in FEATURE_NAMES] for row in usable],
        dtype=np.float64,
    )
    targets = np.asarray([float(_target(row) or 0.0) for row in usable], dtype=np.float64)
    model = HistGradientBoostingRegressor(**hyperparameters).fit(matrix, targets)
    head = export_hist_gradient_boosting(model, FEATURE_NAMES)
    head["objective"] = "clipped_forward_return_q1"
    head["target_clip"] = TARGET_CLIP
    return head


def predict_return(row: dict[str, Any], head: dict[str, Any]) -> float:
    prediction = predict_head(head, feature_map(row))
    return max(-TARGET_CLIP, min(TARGET_CLIP, float(prediction)))


def _rank(values: list[float]) -> list[float]:
    order = sorted(range(len(values)), key=lambda idx: values[idx])
    ranks = [0.0] * len(values)
    for rank, idx in enumerate(order, start=1):
        ranks[idx] = float(rank)
    return ranks


def _correlation(a: list[float], b: list[float]) -> float:
    if len(a) < 2 or len(a) != len(b):
        return 0.0
    mean_a = fmean(a)
    mean_b = fmean(b)
    numerator = sum((x - mean_a) * (y - mean_b) for x, y in zip(a, b))
    denominator = math.sqrt(sum((x - mean_a) ** 2 for x in a)) * math.sqrt(
        sum((y - mean_b) ** 2 for y in b)
    )
    return numerator / denominator if denominator > 0 else 0.0


def _quantile(values: list[float], q: float) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    idx = int(max(0, min(len(ordered) - 1, math.floor((len(ordered) - 1) * q))))
    return ordered[idx]


def selection_metrics(
    rows: list[dict[str, Any]],
    predictions: list[float],
    *,
    tail_fraction: float,
    min_abs_prediction: float,
    round_trip_cost: float = DEFAULT_ROUND_TRIP_COST,
) -> SelectionMetrics:
    usable = usable_rows(rows)
    if len(usable) != len(predictions):
        raise ValueError("prediction count does not match usable rows")

    by_date: dict[str, list[tuple[dict[str, Any], float]]] = defaultdict(list)
    for row, prediction in zip(usable, predictions):
        day = str(row.get("timestamp") or "")[:10]
        by_date[day].append((row, float(prediction)))

    trade_returns: list[float] = []
    daily_returns: list[float] = []
    for items in by_date.values():
        if len(items) < 4:
            continue
        ordered = sorted(items, key=lambda item: item[1])
        count = max(1, math.ceil(len(ordered) * max(0.0, min(0.5, tail_fraction))))
        selected: list[float] = []

        for row, prediction in ordered[-count:]:
            if prediction < min_abs_prediction:
                continue
            realized = float(_target(row) or 0.0)
            selected.append(realized - round_trip_cost)

        for row, prediction in ordered[:count]:
            if prediction > -min_abs_prediction:
                continue
            realized = float(_target(row) or 0.0)
            selected.append(-realized - round_trip_cost)

        if selected:
            trade_returns.extend(selected)
            daily_returns.append(fmean(selected))

    true = [float(_target(row) or 0.0) for row in usable]
    rank_corr = _correlation(_rank(true), _rank([float(value) for value in predictions]))
    return SelectionMetrics(
        trades=len(trade_returns),
        dates=len(daily_returns),
        mean_net_return=fmean(trade_returns) if trade_returns else -1.0,
        median_net_return=median(trade_returns) if trade_returns else -1.0,
        hit_rate=(
            fmean([1.0 if value > 0 else 0.0 for value in trade_returns])
            if trade_returns
            else 0.0
        ),
        mean_daily_selection_return=fmean(daily_returns) if daily_returns else -1.0,
        worst_decile_trade_return=_quantile(trade_returns, 0.10),
        rank_correlation=rank_corr,
    )


def _operating_score(metrics: SelectionMetrics) -> float:
    if metrics.trades < 20 or metrics.dates < 5:
        return -1.0
    # Optimize what survives costs, with modest penalties for unstable tails.
    downside_penalty = max(0.0, -metrics.worst_decile_trade_return) * 0.10
    hit_bonus = max(-0.05, min(0.05, metrics.hit_rate - 0.5)) * 0.02
    return (
        metrics.mean_net_return
        + 0.25 * metrics.median_net_return
        + hit_bonus
        - downside_penalty
    )


def select_hyperparameters(train_rows: list[dict[str, Any]]) -> dict[str, Any]:
    folds = purged_expanding_folds(
        usable_rows(train_rows),
        target_end_field=TARGET_END_FIELD,
        folds=3,
        min_train_dates=60,
    )
    if not folds:
        raise ValueError("insufficient purged temporal folds for adaptive utility selection")

    candidates: list[dict[str, Any]] = []
    for params in HYPERPARAMETER_GRID:
        fold_metrics: list[SelectionMetrics] = []
        for fold_train, fold_valid in folds:
            head = _fit_head(fold_train, dict(params))
            valid = usable_rows(fold_valid)
            predictions = [predict_return(row, head) for row in valid]
            fold_metrics.append(
                selection_metrics(
                    valid,
                    predictions,
                    tail_fraction=0.15,
                    min_abs_prediction=0.008,
                )
            )
        score = fmean([_operating_score(item) for item in fold_metrics])
        candidates.append(
            {
                "hyperparameters": dict(params),
                "cv_score": score,
                "folds": [item.as_dict() for item in fold_metrics],
            }
        )

    winner = max(candidates, key=lambda item: float(item["cv_score"]))
    return {
        "winner": winner,
        "candidates": candidates,
        "fold_count": len(folds),
        "selection_used_test": False,
    }


def select_operating_point(
    train_rows: list[dict[str, Any]],
    validation_rows: list[dict[str, Any]],
    hyperparameters: dict[str, float | int | bool | str],
) -> dict[str, Any]:
    head = _fit_head(train_rows, hyperparameters)
    validation = usable_rows(validation_rows)
    predictions = [predict_return(row, head) for row in validation]
    candidates: list[dict[str, Any]] = []
    for tail_fraction, threshold in OPERATING_GRID:
        metrics = selection_metrics(
            validation,
            predictions,
            tail_fraction=tail_fraction,
            min_abs_prediction=threshold,
        )
        candidates.append(
            {
                "tail_fraction": tail_fraction,
                "min_abs_prediction": threshold,
                "score": _operating_score(metrics),
                "metrics": metrics.as_dict(),
            }
        )
    winner = max(candidates, key=lambda item: float(item["score"]))
    return {"winner": winner, "candidates": candidates, "selection_used_test": False}


def _ridge_metrics(
    train_rows: list[dict[str, Any]],
    eval_rows: list[dict[str, Any]],
    *,
    tail_fraction: float,
) -> SelectionMetrics:
    train = usable_rows(train_rows)
    evaluation = usable_rows(eval_rows)
    artifact = train_weekly_opportunity_model(
        train,
        evaluation,
        model_name="weekly_opportunity_ridge_baseline",
        version="adaptive-audit-baseline",
        tune=False,
    )
    predictions = [predict_weekly_opportunity(row, artifact.params) for row in evaluation]
    return selection_metrics(
        evaluation,
        predictions,
        tail_fraction=tail_fraction,
        min_abs_prediction=0.0,
    )


def _momentum_metrics(
    rows: list[dict[str, Any]],
    *,
    tail_fraction: float,
) -> SelectionMetrics:
    evaluation = usable_rows(rows)
    predictions = [_number(row.get("momentum_20")) for row in evaluation]
    return selection_metrics(
        evaluation,
        predictions,
        tail_fraction=tail_fraction,
        min_abs_prediction=0.0,
    )


def train_and_audit(rows: list[dict[str, Any]], *, version: str = MODEL_VERSION) -> dict[str, Any]:
    train = usable_rows([row for row in rows if row.get("split") == "train"])
    validation = usable_rows([row for row in rows if row.get("split") == "validation"])
    blind_test = usable_rows([row for row in rows if row.get("split") == "test"])
    if not train or not validation or not blind_test:
        raise ValueError("adaptive utility audit requires train, validation, and test splits")

    tuning = select_hyperparameters(train)
    hyperparameters = dict(tuning["winner"]["hyperparameters"])
    operating = select_operating_point(train, validation, hyperparameters)
    tail_fraction = float(operating["winner"]["tail_fraction"])
    threshold = float(operating["winner"]["min_abs_prediction"])

    validation_head = _fit_head(train, hyperparameters)
    validation_predictions = [predict_return(row, validation_head) for row in validation]
    adaptive_validation = selection_metrics(
        validation,
        validation_predictions,
        tail_fraction=tail_fraction,
        min_abs_prediction=threshold,
    )
    ridge_validation = _ridge_metrics(train, validation, tail_fraction=tail_fraction)
    momentum_validation = _momentum_metrics(validation, tail_fraction=tail_fraction)

    # Every choice is frozen before test. Refit on all pre-test eligible labels,
    # then open the sealed test exactly once for an unbiased audit.
    pretest = [*train, *validation]
    final_head = _fit_head(pretest, hyperparameters)
    blind_predictions = [predict_return(row, final_head) for row in blind_test]
    adaptive_blind = selection_metrics(
        blind_test,
        blind_predictions,
        tail_fraction=tail_fraction,
        min_abs_prediction=threshold,
    )
    ridge_blind = _ridge_metrics(pretest, blind_test, tail_fraction=tail_fraction)
    momentum_blind = _momentum_metrics(blind_test, tail_fraction=tail_fraction)

    validation_dominates = (
        adaptive_validation.mean_net_return > ridge_validation.mean_net_return
        and adaptive_validation.mean_net_return > momentum_validation.mean_net_return
    )
    blind_dominates = (
        adaptive_blind.mean_net_return > ridge_blind.mean_net_return
        and adaptive_blind.mean_net_return > momentum_blind.mean_net_return
        and adaptive_blind.hit_rate >= ridge_blind.hit_rate - 0.03
        and adaptive_blind.trades >= 20
    )

    return {
        "model_name": MODEL_NAME,
        "version": version,
        "horizon": "q1_10_sessions",
        "target": "clipped_forward_return_q1",
        "feature_names": list(FEATURE_NAMES),
        "round_trip_cost": DEFAULT_ROUND_TRIP_COST,
        "params": {
            "head": final_head,
            "hyperparameters": hyperparameters,
            "operating": {
                "tail_fraction": tail_fraction,
                "min_abs_prediction": threshold,
            },
            "canonical_serving_enabled": False,
            "paper_enabled": False,
            "live_enabled": False,
        },
        "selection": {
            "hyperparameter_cv": tuning,
            "operating_point": operating,
            "test_used_for_selection": False,
            "blind_test_opened_after_freeze": True,
        },
        "metrics": {
            "validation": {
                "adaptive": adaptive_validation.as_dict(),
                "weekly_ridge": ridge_validation.as_dict(),
                "momentum_20": momentum_validation.as_dict(),
                "dominates_baselines": validation_dominates,
            },
            "blind_test": {
                "adaptive": adaptive_blind.as_dict(),
                "weekly_ridge": ridge_blind.as_dict(),
                "momentum_20": momentum_blind.as_dict(),
                "dominates_baselines": blind_dominates,
            },
        },
        "promotion_ready_for_strategy_replay": bool(validation_dominates and blind_dominates),
    }


def _load_rows(path: Path) -> list[dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(payload, dict) and isinstance(payload.get("rows"), list):
        return [dict(row) for row in payload["rows"]]
    if isinstance(payload, list):
        return [dict(row) for row in payload]
    raise ValueError("unsupported dataset payload")


def main() -> None:
    parser = argparse.ArgumentParser(description="Train and blind-audit adaptive net utility model")
    parser.add_argument("--dataset", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--version", default=MODEL_VERSION)
    parser.add_argument("--require-dominance", action="store_true")
    args = parser.parse_args()

    report = train_and_audit(_load_rows(Path(args.dataset)), version=args.version)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(report["metrics"], ensure_ascii=False, indent=2))
    print(f"promotion_ready_for_strategy_replay={report['promotion_ready_for_strategy_replay']}")
    if args.require_dominance and report["promotion_ready_for_strategy_replay"] is not True:
        raise SystemExit("adaptive net utility failed validation/blind baseline dominance")


if __name__ == "__main__":
    main()
